categories:
  maximum: 30
  limit: 5
comments:
  content_max_length: 140
show_limit:
  show_5: 5
  show_10: 10
  show_15: 15
  show_20: 20
  show_30: 30
  show_50: 50
product:
  featured: 12
  hot: 5
  limit: 8
  validates:
    price_maximum: 8
ratings:
  average: 0
order_details:
  quantity:
    default: 1
order_status:
  pending: "pending"
  delivered: "delivered"
  canceled: "canceled"
filters:
  min_default: 0
  max_default: 1000000
  step: 500000
show_more: 1
import:
  header: 1
  row: 2
